import type { NextPage } from "next";
import Head from "next/head";
import styles from "./Notification.module.css";
import * as React from "react";
import { signOut, useSession } from "next-auth/react";
import Link from "next/link";
import { Container, Card, Button, Grid, Text } from "@nextui-org/react";
import "react-activity-feed/dist/index.css";
import { connect } from "getstream";
import {
  StreamApp,
  NotificationDropdown,
  FlatFeed,
  LikeButton,
  Activity,
  CommentList,
  CommentField,
  StatusUpdateForm,
  FollowButton,
  NotificationFeed,
} from "react-activity-feed";
import stream from "getstream";
import { useEffect } from "react";
import NavBar from "../components/NavBar";



const apiKey = process.env.NEXT_PUBLIC_STREAM_API_KEY as string;
const appId = process.env.NEXT_PUBLIC_STREAM_APP_ID as string;

const Notification: NextPage = (props) => {
  const session = useSession();
  const userToken = session.data?.user?.userToken;
  const username = session.data?.user?.username;

  
  const apiKey = process.env.NEXT_PUBLIC_STREAM_API_KEY as string;
  const appId = process.env.NEXT_PUBLIC_STREAM_APP_ID as string;


  let stream = require('getstream');



  const client = stream.connect(apiKey, userToken, appId);


  // For the feed group 'user' and user id 'eric' get the feed
  // The user token is generated server-side for this user

  // this MADE the notification feed
  const notificationFeed = client.feed('notification', username, userToken);




  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Home for</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
     

          <h1 className={styles.title}>
            Notifications
          </h1>
          <Link href="/home">
            <Button>Home</Button>
          </Link>
          <StreamApp apiKey={apiKey} appId={appId} token={userToken}>

            <NotificationDropdown notify />
            <NotificationFeed
              userId={username}
              notify
              feedGroup="notification"
            />
          </StreamApp>
          <Card className={styles.header}>
            <Button onClick={signOut}>Sign Out</Button>
          </Card>
        </main>
      </div>
    </>
  );
};

export async function getServerSideProps() {
  let stream = require('getstream');



  const client = stream.connect(apiKey, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZ2xvYmFsVXNlciJ9.eiHWrONEGfoYxVDsSCNONfX7xqlar6QRbY0_ZCC6tc0', appId);



  //worked!

  const alexFlatFeed = client.feed('home', 'alex', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYWxleCJ9.Dj99sRGyL1duxpxvR1ulLw6IEnuSAyqv07tlD4tNGoQ');
  // const jakeFlatFeed = client.feed('home', 'jake', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiamFrZSJ9.DcUg0vGH-JPuy4Tv0HYXuWvRdnNqEajgu_YuFVXmK9w');
  // alexFlatFeed.follow('user', 'jake', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiamFrZSJ9.DcUg0vGH-JPuy4Tv0HYXuWvRdnNqEajgu_YuFVXmK9w');
  alexFlatFeed.follow('user', 'lottie', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoibG90dGllIn0.JtPcDkX2Ax-NSP2vbNvZOwH0ZLXs97vEYp219fthvGk');

  // const alexFlatFeed

  return {
    props: {},
  };
}

export default Notification;
